### ISSUE TITLE
[Feature]: Automatically set customerIpAddress

### ISSUE THREAD

**Issue by holtwick** [PaddleHQ/paddle-js-wrapper#57] opened 2024-08-28 13:33 UTC
### Tell us about your feature request

In Paddle Classic the customer IP would be read out automatically, but Billing requires to use an external service. See https://developer.paddle.com/build/checkout/build-pricing-page#pass-location

### What problem are you looking to solve?

Why have additional calls if the IP is already available in the PricingPreview call? It would be much easier to not be required to have this additional step for integration.

### How important is this suggestion to you?

Nice to have

**Comment by vijayasingam-paddle** [comment] 2024-08-28 13:53
Hi @holtwick, 
Thank you for the feedback. 

I agree with you. Expecting sellers to pass an IP address is not an ideal scenario.

We decided to skip IP address detection because the API could be called from a backend service and defaulting to the server's IP address will not be very helpful. 

With that said, we are working on an opt-in solution that should allow us to detect the IP address if the sellers wants us to do so. Unfortunately, we do not have an ETA on the release date

I will close this issue as it is a duplicate of #34.

Please follow issue #34 to get notified when this issue is resolved. 

Thank you.

**Closed by vijayasingam-paddle** 2024-08-28 13:53 UTC
